export default [
  'Supermercado',
  'Restaurante',
  'Avião',
  'Quartel',
  'Estúdio de Música',
  'Igreja',
  'Banheiro',
  'Cemitério',
  'Ótica',
  'Hospital',
  'Sala de Cirurgia',
  'Loja de Antiguidades',
  'Disney',
  'Ônibus',
  'Zoológico',
  'Submarino',
  'Cruzeiro Marítimo',
  'Feira',
  'Vinícula',
  'Circo',
  'Teatro',
  'Trem de passageiros',
  'Quadra de tênis',
  'Campo de futebol',
  'Banco',
  'Escola',
  'Faculdade',
  'Spa',
  'Praia',
  'Navio pirata',
  'Delegacia de polícia',
  'Prisão',
  'Salão de cabelereiros',
  'Congresso',
  'Loja de cosméticos',
  'Discoteca',
  'Boteco',
  'Farmácia',
  'Quarto de motel',
  'Museu',
  'Ateliê de pintura',
  'Brechó',
  'Shopping',
  'Lavanderia',
  'Barbearia',
  'Castelo medieval',
  'Hotel',
  'Jardim',
  'Lua',
  'Monte Everest',
  'Parque',
  'Festa fantasia',
  'Chá de bebê',
  'Despedida de solteiro',
  'Biblioteca',
  'Casamento',
  'Descobrimento do Brasil',
  'Tribo indígena',
  'Segunda Guerra Mundial',
  'Enem',
  'Show de Rock',
  'Parque de Diversões',
  'Clube',
  'Hospício',
  'Acampamento',
  'Apocalipse zumbi',
  'Oficina mecânica',
  'Titanic',
  'Pântano',
  'Selva',
  'Boliche',
  'Padaria',
  'Terminal de ônibus',
  'Cinema',
  'Dentista',
  'Cachoeira',
  'Carnaval',
  'Petshop',
  'Patinação no gelo',
  'Fazenda',
  'Ilha deserta',
  'Bosque',
  'Estacionamento',
  'Favela',
  'Escritório',
  'Lotérica',
  'Posto de combustível',
  'Caverna',
  'Lan house',
  'Locadora de filmes',
  'Cafeteria',
  'Táxi',
  'Asilo',
  'Pirâmide do Egito',
  'Vaticano',
  'Cassino',
  'Parque dos Dinossauros',
  'Festa de Aniversário',
  'Formatura',
  'Fliperama'
]
